### ISSUE TITLE
Autotools cleanups

### ISSUE THREAD

**Issue by ao2** [DIGImend/hidrd#7]
Hi Nikolai,

here are some autotools cleanups I had laying around:  http://ao2.it/tmp/hidrd-autotools-cleanup.patch

You can apply the changes with ```git am```.

There are still a few warnings with the current build files:
```
include/hidrd/usage/Makefile.am:22: warning: '%'-style pattern rules are a GNU make extension
lib/usage/Makefile.am:31: warning: '%'-style pattern rules are a GNU make extension
```

I am not sure if these are worth fixing.

Ciao,
  Antonio

**Comment by spbnick** [comment]
Thanks a lot, Antonio.
I'll try to get around to this this week.

**Comment by spbnick** [comment]
These all seem fine. Pushed with only one typo in a commit subject fixed.
Thank you very much, Antonio!
